import org.junit.jupiter.api.Test;

// Generated by RandoopHarvester (Mode 4, Randoop source strategy).
// Source inputs: Randoop-harvested Order objects. MR: developer-owned (OrderMetamorphicSpec).
public class GeneratedOrderUtilRandoopTest {

    @Test
    public void test_0() {
        Order source = new Order(java.util.Arrays.asList(new LineItem("item1", 97, 4.0), new LineItem("item1", 97, 4.0), new LineItem("item1", 97, 4.0), new LineItem("item1", 97, 4.0), new LineItem("item1", 97, 4.0)));
        double sourceOutput = OrderUtil.calculateTotal(source);
        Order followUp = OrderMetamorphicSpec.generateFollowUp(source);
        double followUpOutput = OrderUtil.calculateTotal(followUp);
        OrderMetamorphicSpec.assertRelation(sourceOutput, followUpOutput);
    }

    @Test
    public void test_1() {
        Order source = new Order(new java.util.ArrayList<LineItem>());
        double sourceOutput = OrderUtil.calculateTotal(source);
        Order followUp = OrderMetamorphicSpec.generateFollowUp(source);
        double followUpOutput = OrderUtil.calculateTotal(followUp);
        OrderMetamorphicSpec.assertRelation(sourceOutput, followUpOutput);
    }

    @Test
    public void test_2() {
        Order source = new Order(java.util.Arrays.asList(new LineItem("item_with_max_length_name_max_length_name_max_length_name_max_length_name", 1000000, 100.0), new LineItem("item_with_max_length_name_max_length_name_max_length_name_max_length_name", 1000000, 100.0), new LineItem("item1", 100, 0.0), new LineItem("item_with_max_length_name_max_length_name_max_length_name_max_length_name", 100, 100.0), new LineItem("long_item_name_long_item_name_long_item_name_long_item_name_long_item_name", 3, 10.0), new LineItem("item_with_max_length_name_max_length_name_max_length_name_max_length_name", 10, 100.0), new LineItem("item_with_max_length_name_max_length_name_max_length_name_max_length_name", 1000000, 100.0), new LineItem("item_with_max_length_name_max_length_name_max_length_name_max_length_name", 1000000, 100.0), new LineItem("item_with_max_length_name_max_length_name_max_length_name_max_length_name", 0, 6.0)));
        double sourceOutput = OrderUtil.calculateTotal(source);
        Order followUp = OrderMetamorphicSpec.generateFollowUp(source);
        double followUpOutput = OrderUtil.calculateTotal(followUp);
        OrderMetamorphicSpec.assertRelation(sourceOutput, followUpOutput);
    }

    @Test
    public void test_3() {
        Order source = new Order(java.util.Arrays.asList(new LineItem("long_item_name_long_item_name_long_item_name_long_item_name_long_item_name", 3, 10.0), new LineItem("item_with_space_between_words", 2, 1000000.0), new LineItem("item_with_max_length_name_max_length_name_max_length_name_max_length_name", 10, 100.0), new LineItem("item_with_max_length_name_max_length_name_max_length_name_max_length_name", 1000000, 100.0), new LineItem("item_with_max_length_name_max_length_name_max_length_name_max_length_name", 1000000, 100.0), new LineItem("item_with_space_between_words", 2, 1000000.0), new LineItem("item_with_max_length_name_max_length_name_max_length_name_max_length_name", 1000000, 100.0), new LineItem("item_with_max_length_name_max_length_name_max_length_name_max_length_name", 1000000, 100.0), new LineItem("item_with_max_length_name_max_length_name_max_length_name_max_length_name", 4, 100.0), new LineItem("item_with_max_length_name_max_length_name_max_length_name_max_length_name", 1000000, 100.0), new LineItem("item_with_max_length_name_max_length_name_max_length_name_max_length_name", 1000000, 100.0), new LineItem("item1", 100, 0.0)));
        double sourceOutput = OrderUtil.calculateTotal(source);
        Order followUp = OrderMetamorphicSpec.generateFollowUp(source);
        double followUpOutput = OrderUtil.calculateTotal(followUp);
        OrderMetamorphicSpec.assertRelation(sourceOutput, followUpOutput);
    }

    @Test
    public void test_4() {
        Order source = new Order(java.util.Arrays.asList(new LineItem("item3", 52, 1.0), new LineItem("item3", 52, 1.0), new LineItem("item3", 52, 1.0), new LineItem("item3", 52, 1.0), new LineItem("item3", 52, 1.0), new LineItem("item2", 10, 32.0), new LineItem("item2", 10, 32.0), new LineItem("item3", 4, 1.0), new LineItem("item1", 52, 0.5), new LineItem("item3", 52, 1.0)));
        double sourceOutput = OrderUtil.calculateTotal(source);
        Order followUp = OrderMetamorphicSpec.generateFollowUp(source);
        double followUpOutput = OrderUtil.calculateTotal(followUp);
        OrderMetamorphicSpec.assertRelation(sourceOutput, followUpOutput);
    }

    @Test
    public void test_5() {
        Order source = new Order(java.util.Arrays.asList(new LineItem("item3", 100, 1.0), new LineItem("item3", 52, 1.0), new LineItem("item3", 1000000, 1.0), new LineItem("long_item_name_long_item_name_long_item_name_long_item_name_long_item_name", 100, 100.0), new LineItem("item3", 52, 1.0), new LineItem("item3", 2147483647, 1.0), new LineItem("item3", 52, 1.0)));
        double sourceOutput = OrderUtil.calculateTotal(source);
        Order followUp = OrderMetamorphicSpec.generateFollowUp(source);
        double followUpOutput = OrderUtil.calculateTotal(followUp);
        OrderMetamorphicSpec.assertRelation(sourceOutput, followUpOutput);
    }

}
