import java.util.List;

/**
 * Emits a Mode 4 JUnit 5 candidate test class from harvested Order objects.
 *
 * <p>One @Test per source input. Each test constructs the concrete source, runs the SUT,
 * calls the DEVELOPER-owned follow-up transform and assertion (OrderMetamorphicSpec), and
 * runs the SUT on the follow-up. The emitter writes no relation logic of its own -- it only
 * wires inputs into the developer's MR, exactly as Mode 4 requires. The generated class has
 * no Randoop dependency, so it runs under Soham's existing GeneratedTestRunner / splitter.</p>
 */
public final class Mode4TestEmitter {

    private Mode4TestEmitter() {
    }

    public static String emit(String className, List<Order> sources) {
        StringBuilder sb = new StringBuilder();
        sb.append("import org.junit.jupiter.api.Test;\n\n");
        sb.append("// Generated by RandoopOrderHarvester (Mode 4, Randoop source strategy).\n");
        sb.append("// Source inputs: Randoop-harvested Order objects. MR: developer-owned (OrderMetamorphicSpec).\n");
        sb.append("public class ").append(className).append(" {\n\n");

        for (int i = 0; i < sources.size(); i++) {
            sb.append("    @Test\n");
            sb.append("    public void test_").append(i).append("() {\n");
            sb.append("        Order source = ").append(constructionCode(sources.get(i))).append(";\n");
            sb.append("        double sourceOutput = OrderUtil.calculateTotal(source);\n");
            sb.append("        Order followUp = OrderMetamorphicSpec.generateFollowUp(source);\n");
            sb.append("        double followUpOutput = OrderUtil.calculateTotal(followUp);\n");
            sb.append("        OrderMetamorphicSpec.assertRelation(sourceOutput, followUpOutput);\n");
            sb.append("    }\n\n");
        }

        sb.append("}\n");
        return sb.toString();
    }

    /** Emit Java that reconstructs the given Order, e.g. new Order(java.util.Arrays.asList(new LineItem(...))). */
    static String constructionCode(Order order) {
        List<LineItem> items = order.getItems();
        if (items.isEmpty()) {
            return "new Order(new java.util.ArrayList<LineItem>())";
        }
        StringBuilder sb = new StringBuilder();
        sb.append("new Order(java.util.Arrays.asList(");
        for (int i = 0; i < items.size(); i++) {
            LineItem item = items.get(i);
            if (i > 0) {
                sb.append(", ");
            }
            sb.append("new LineItem(\"").append(escape(item.getName())).append("\", ")
              .append(item.getQuantity()).append(", ")
              .append(item.getUnitPrice()).append(")");
        }
        sb.append("))");
        return sb.toString();
    }

    private static String escape(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
